# Generated by Django 5.0.6 on 2024-06-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='arr_waterlevel',
        ),
    ]
