# Generated by Django 5.0.6 on 2024-06-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('curr_rainfall', models.FloatField(default=0)),
                ('curr_temp', models.FloatField(default=0)),
                ('curr_windspeed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DaywisePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('day1_rainfall', models.FloatField(default=0)),
                ('day2_rainfall', models.FloatField(default=0)),
                ('day3_rainfall', models.FloatField(default=0)),
                ('day4_rainfall', models.FloatField(default=0)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awsstations.awsstation')),
            ],
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awsstations.awsstation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('station_code', models.IntegerField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('WarningLevel', models.IntegerField(default=0)),
                ('neareststation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awsstations.awsstation')),
            ],
        ),
    ]
