# Generated by Django 5.0.6 on 2024-06-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsstations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('hr_24_rainfall', models.JSONField(default=dict)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awsstations.awsstation')),
            ],
        ),
    ]
